name: anjas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: anjas
        run: |
          unzip path/to/cihuy.zip -d path/to/destination/
